### ISSUE TITLE
BEHAVIORAL DESING PATTERN

### ISSUE THREAD

**Issue by lnsalaza** [ShaunJorstad/Comp-350-Drones#88]
Hello, as a task related to the Software Design course, my gruop and I were given the task of analyzing this project, where we could see that its design could include a Desing Patter, Decorator Patter to be more specific.

The current implementation assumes the possibility of creating drones with an arbitrary load weight, which is not in agreement with reality, within the real world it is more feasible to create drones with a previous prototype. To solve this, the implementation of the Chain of Responsibility behavior pattern is proposed, since not only would we have prototypes of drones with specific sizes and weight of load, which is more accurate to reality, but also that responsibility could be managed of each one depending on the weight of the package you want to send. 
![Tarea Patrones - Drone-Delivery-Simulation - Chain of Responsability](https://user-images.githubusercontent.com/76917298/128097897-97a14d53-0104-4286-9835-2b386d7a3344.png)

**Comment by EricMartin17** [comment]
Our implementation does allow the user to set the carrying capacity for the drone fleet. However each drone in the fleet is identical. It would be an intriguing to see if we could create a fleet of different drones and then use the Chain of Responsibility to distribute the packages for improvement in delivery time while minimizing the size of the drones.

![DroneSettings](https://user-images.githubusercontent.com/44842271/128219629-cbdbf79c-44da-40d6-a79a-9d22132a4df8.PNG)
